language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
cache: pip
addons:
  ssh_known_hosts: 157.230.188.74
before_install:
- openssl aes-256-cbc -K $encrypted_92725ca94bf5_key -iv $encrypted_92725ca94bf5_iv
  -in deploy-key.enc -out deploy-key -d
install:
- pip install numpy scipy>=0.18.0 sphinx sphinx_rtd_theme
- pip install --verbose --editable .
script:
- python3 setup.py tests
- python3 setup.py docs
after_success:
- bash docs/deploy_script.sh
